# Generated by Django 2.1.2 on 2018-10-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter summary', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prospects', models.TextField(help_text='Enter a brief description of the project', max_length=1000)),
                ('investors', models.TextField(help_text='Enter investors of the project', max_length=1000)),
                ('pnc', models.TextField(help_text='Enter a pros & cons of the project', max_length=1000)),
                ('code', models.CharField(help_text='Project Code', max_length=13, verbose_name='Code')),
                ('engagement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Engagement')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter summary', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.ManyToManyField(help_text='Select sector for this project', to='projects.Sector'),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Stage'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(help_text='Select a member for this project', to='projects.Team'),
        ),
    ]
    atomic = False