# Generated by Django 2.1.2 on 2018-10-29 16:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Members',
        ),
    ]
    atomic = False