# Generated by Django 2.1.2 on 2018-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0002_auto_20181029_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
