# Generated by Django 2.1.2 on 2018-10-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0003_auto_20181029_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(help_text='Select a member for this project', to='projects.Members'),
        ),
    ]
