# Generated by Django 2.1.2 on 2018-12-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, help_text='Date Format- YYYY-MM-DD', null=True),
        ),
    ]
