# Generated by Django 2.1.2 on 2018-12-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20181213_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='prospects',
            new_name='description',
        ),
    ]
