# Generated by Django 2.1.2 on 2018-12-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20181213_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='competitor',
            field=models.TextField(blank=True, help_text='Enter competitors', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='next_steps',
            field=models.TextField(blank=True, help_text='Suggest next steps ', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.TextField(blank=True, help_text='Enter source', max_length=1000, null=True),
        ),
    ]
