# Generated by Django 2.1.2 on 2018-12-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20181213_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter summary', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter summary', max_length=1000)),
                ('fund_size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
                ('investments', models.IntegerField(help_text='Portfolio/Investments', max_length=3, null=True, verbose_name='No. Of Investments')),
                ('companies', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pnc',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='competitor',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='investors',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='projects.Member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='next_steps',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.ManyToManyField(to='projects.Sector'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.pDesignation'),
        ),
        migrations.AddField(
            model_name='partner',
            name='focus',
            field=models.ManyToManyField(to='projects.Sector'),
        ),
        migrations.AddField(
            model_name='partner',
            name='locate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Location'),
        ),
        migrations.AddField(
            model_name='investor',
            name='partner',
            field=models.ManyToManyField(to='projects.Partner'),
        ),
    ]
