# Generated by Django 2.1.2 on 2018-12-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20181227_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='locate',
            new_name='location',
        ),
    ]
