# Generated by Django 2.1.2 on 2018-12-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
