# Generated by Django 2.1.2 on 2018-12-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20181228_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(null=True, upload_to='projects/documents/'),
        ),
    ]
