# Generated by Django 2.1.2 on 2018-12-28 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20181228_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Investor'),
        ),
    ]
