# Generated by Django 2.1.2 on 2018-12-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20181228_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='fund',
            new_name='investor',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='focus',
            new_name='sector',
        ),
    ]
