# Generated by Django 2.1.2 on 2019-01-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20190101_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialouge',
            name='member',
        ),
    ]
