# Generated by Django 2.1.2 on 2019-01-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_dialouge_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialouge',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Member'),
        ),
    ]
