# Generated by Django 2.1.2 on 2019-01-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20190102_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='investors',
        ),
        migrations.AddField(
            model_name='project',
            name='investors',
            field=models.ManyToManyField(to='projects.Investor'),
        ),
    ]
