# Generated by Django 2.1.2 on 2019-01-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20190102_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document', models.FileField(null=True, upload_to='projects/documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.AddField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
    ]
