# Generated by Django 2.1.2 on 2019-01-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20190102_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DealStage',
        ),
        migrations.RemoveField(
            model_name='projectinstance',
            name='project',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='companies',
        ),
        migrations.DeleteModel(
            name='ProjectInstance',
        ),
        migrations.AddField(
            model_name='companies',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Partner'),
        ),
    ]
