# Generated by Django 2.1.2 on 2019-01-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20190103_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='projects.Partner'),
        ),
    ]
