# Generated by Django 2.1.2 on 2019-01-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20190103_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='companies',
            field=models.ManyToManyField(to='projects.Companies'),
        ),
    ]
