# Generated by Django 2.1.2 on 2019-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20190103_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='companies',
        ),
        migrations.AddField(
            model_name='partner',
            name='companies',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
