# Generated by Django 2.1.2 on 2019-01-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20190103_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='next_steps',
        ),
    ]
