# Generated by Django 2.1.2 on 2019-01-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_remove_project_next_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter summary', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='funding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Stage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.DealStage'),
        ),
    ]
