# Generated by Django 2.1.2 on 2019-01-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20190103_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDcomp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='competitor',
        ),
        migrations.AddField(
            model_name='project',
            name='competitor',
            field=models.ManyToManyField(to='projects.VDcomp'),
        ),
    ]
