# Generated by Django 2.1.2 on 2019-01-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20190103_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='investors',
            new_name='investor',
        ),
    ]
