# Generated by Django 2.1.2 on 2019-01-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20190103_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='stage',
            new_name='dealstage',
        ),
    ]
