# Generated by Django 2.1.2 on 2019-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20190103_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='if_other_investor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
