# Generated by Django 2.1.2 on 2019-01-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_project_if_other_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter director name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='metric',
            field=models.TextField(blank=True, help_text='Total funding received till date or Company valuation', max_length=500),
        ),
        migrations.AlterField(
            model_name='investor',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='investments',
            field=models.IntegerField(help_text='Portfolio/Investments', null=True, verbose_name='No. Of Investments'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.CharField(blank=True, help_text='Leave blank if you dont know the loan amount yet.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(help_text='Enter Industry Sector', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Director'),
        ),
    ]
