# Generated by Django 2.1.2 on 2019-01-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20190107_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ManyToManyField(help_text='Only Select partners relevant to this engagement', to='projects.Partner'),
        ),
    ]
