# Generated by Django 2.1.2 on 2019-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_project_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='metric',
            field=models.TextField(blank=True, help_text='Total funding received till date or Company valuation', max_length=100),
        ),
    ]
