# Generated by Django 2.1.2 on 2019-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20190107_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='metric',
            field=models.CharField(blank=True, help_text='Total funding received till date or Company valuation', max_length=100),
        ),
    ]
