# Generated by Django 2.1.2 on 2019-01-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20190107_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ManyToManyField(blank=True, help_text='Only Select partners relevant to this engagement', to='projects.Partner'),
        ),
    ]
