# Generated by Django 2.1.2 on 2019-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20190107_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='metric',
        ),
        migrations.AddField(
            model_name='project',
            name='equity_LTD',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='loan_Amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='competitor',
            field=models.ManyToManyField(help_text='Leave blank if you dont know the loan amount yet.', to='projects.VDcomp'),
        ),
    ]
