# Generated by Django 2.1.2 on 2019-01-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_dialouge_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialouge',
            name='member',
        ),
    ]
