# Generated by Django 2.1.2 on 2019-01-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_remove_dialouge_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('dealstage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.DealStage')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
            ],
        ),
    ]
