# Generated by Django 2.1.2 on 2019-01-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_dsdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsdate',
            name='comm',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
