# Generated by Django 2.1.2 on 2019-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_remove_dsdate_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_step',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
