# Generated by Django 2.1.2 on 2019-01-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_project_next_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsdate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
