# Generated by Django 2.1.2 on 2019-01-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20190109_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closure_month',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
