# Generated by Django 2.1.2 on 2019-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20190110_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='funding_Round',
            new_name='funding_Satge',
        ),
        migrations.AlterField(
            model_name='project',
            name='competitor',
            field=models.ManyToManyField(to='projects.VDcomp'),
        ),
        migrations.AlterField(
            model_name='project',
            name='loan_Amount',
            field=models.CharField(blank=True, help_text='Leave blank if you dont know the loan amount yet.', max_length=50),
        ),
    ]
