# Generated by Django 2.1.2 on 2019-01-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_auto_20190114_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcompanies',
            name='remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='last_round',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='valuation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
