# Generated by Django 2.1.2 on 2019-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20190121_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
