# Generated by Django 2.1.2 on 2019-01-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20190121_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='similar_companies',
            field=models.TextField(blank=True, help_text='Any Competition ?', max_length=500),
        ),
    ]
