# Generated by Django 2.1.2 on 2019-01-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_project_similar_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='next_step',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
