# Generated by Django 2.1.2 on 2019-01-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20190121_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialouge',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
